DROP PROCEDURE IF EXISTS  UpdateBestsellers;

DELIMITER $$

CREATE PROCEDURE UpdateBestsellers()
BEGIN
    DECLARE RENT_COUNT, BOOKS_READ INT;
    DECLARE FINISHED INT DEFAULT 0;
    DECLARE BOOKS CURSOR FOR SELECT BOOK_ID FROM RENTS;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;
    OPEN BOOKS;

    WHILE (FINISHED = 0) DO
        FETCH BOOKS INTO RENT_COUNT;
        SELECT COUNT(*) FROM RENTS WHERE BOOK_ID = RENT_ID INTO BOOKS_READ;
        IF (BOOKS_READ > 2) THEN
            UPDATE BOOKS SET BOOKS.BESTSELLER = TRUE WHERE BOOK_ID = RENT_COUNT;
            COMMIT;
            END IF;
        END WHILE;
    CLOSE BOOKS;
    END $$

DELIMITER ;

CALL UpdateBestsellers();
SELECT * FROM BOOKS;
