DROP PROCEDURE IF EXISTS LibraryIndexes;

DELIMITER $$

CREATE PROCEDURE LibraryIndexes()
BEGIN
    EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = 'John';
    CREATE INDEX READERS_FIRST_NAME ON READERS (FIRSTNAME);
    CREATE INDEX READERS_LAST_NAME ON READERS (LASTNAME);
    CREATE INDEX TITLE_INDEX ON BOOKS (TITLE);
    EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME - 'John';
END $$

DELIMITER ;