/1
SELECT ISSUES.ID, NAME
FROM ISSUES, ISSUESLISTS
WHERE ISSUES.ISSUESLIST_ID = ISSUESLISTS.ID;

/2
SELECT ISSUES.ID, FIRSTNAME, LASTNAME
FROM ISSUES, USERS
WHERE ISSUES.USER_ID_ASSIGNEDTO  = USERS.ID;

/3
SELECT U.FIRSTNAME, U.LASTNAME,   COUNT(*) AS USERS_WITH_TASK
FROM ISSUES I
JOIN USERS U ON I.USER_ID_ASSIGNEDTO = U.ID
GROUP BY U.ID
HAVING COUNT(*) >= 1
ORDER BY U.LASTNAME, U.FIRSTNAME;